Models/Equipe.cs
using System;
using System.Collections.Generic;
using System.IO;
using ProjetoEPlayers.Interfaces;

namespace ProjetoEPlayers.Models
{
    public class Equipe : EplayersBase , IEquipe
    {
        public int IdEquipe { get; set; }
        public string Nome { get; set; }
        public string Imagem { get; set; }

        private const string PATH = "Database/equipe.csv";

        public Equipe(){
            CreateFolderAndFile(PATH);
        }

        /// <summary>
        /// Cria uma equipe
        /// </summary>
        /// <param name="e">Equipe a ser criada</param>
        public void Create(Equipe e)
        {
            string[] linhas = { PrepararLinha(e) };
            File.AppendAllLines(PATH, linhas);
        }

        /// <summary>
        /// Deleta uma linha do CSV
        /// </summary>
        /// <param name="IdEquipe">Termo que será usado para excluir uma linha do CSV</param>
        public void Delete(int IdEquipe)
        {
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(";")[0] == IdEquipe.ToString());
            RewriteCSV(PATH, linhas);
        }

        /// <summary>
        /// Lê as linhas de equipe no CSV
        /// </summary>
        /// <returns>Linhas de equipe do CSV</returns>
        public List<Equipe> ReadAll()
        {
            List<Equipe> equipes = new List<Equipe>();
            string[] linhas = File.ReadAllLines(PATH);
            foreach (var item in linhas)
            {
                string[] linha = item.Split(";");
                Equipe equipe = new Equipe();
                equipe.IdEquipe = Int32.Parse(linha[0]);
                equipe.Nome = linha[1];
                equipe.Imagem = linha[2];

                equipes.Add(equipe);
            }
            return equipes;
        }

        /// <summary>
        /// Atualiza alguma linha do CSV
        /// </summary>
        /// <param name="e">Equipe que será atualizada</param>
        public void Update(Equipe e)
        {
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(";")[0] == e.IdEquipe.ToString());
            linhas.Add(PrepararLinha(e));
            RewriteCSV(PATH, linhas);
        }
        
        /// <summary>
        /// Prepara a linha para ir ao CSV
        /// </summary>
        /// <param name="e">Equipe que terá a linha preparada</param>
        /// <returns>Linha preparada para o CSV</returns>
        private string PrepararLinha(Equipe e){
            return $"{e.IdEquipe};{e.Nome};{e.Imagem}";
        }
    }
}

Controllers/EquipeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjetoEPlayers.Models;

namespace ProjetoEPlayers.Controllers
{
    
    public class EquipeController : Controller
    {
        Equipe equipeModel = new Equipe();

        public IActionResult Index()
        {
            ViewBag.Equipes = equipeModel.ReadAll();
            return View();
        }

        public IActionResult Cadastrar(IFormCollection form)
        {
        
            Equipe novaEquipe   = new Equipe();
            novaEquipe.IdEquipe = Int32.Parse(form["IdEquipe"]);
            novaEquipe.Nome     = form["Nome"];
            novaEquipe.Imagem   = form["Imagem"];

            // Upload de imagem inicio
            var file    = form.Files[0];
            var folder  = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Equipes");

            if(file != null)
            {
                if(!Directory.Exists(folder)){
                    Directory.CreateDirectory(folder);
                }

                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/", folder, file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))  
                {  
                    file.CopyTo(stream);  
                }
                novaEquipe.Imagem   = file.FileName;
            }
            else
            {
                novaEquipe.Imagem   = "padrao.png";
            }
            // Upload de imagem final

            equipeModel.Create(novaEquipe);            
            ViewBag.Equipes = equipeModel.ReadAll();

            return LocalRedirect("~/Equipe");

        }

        [Route("[controller]/{id}")]
        public IActionResult Excluir(int id)
        {
            equipeModel.Delete(id);
            ViewBag.Equipes = equipeModel.ReadAll();
            return LocalRedirect("~/Equipe");
        }
        
    }
}

Views/Equipe/Index.cshtml
@model Equipe
    @{
        ViewData["Title"] = "Equipes";
    }

    <div class="titulo_pagina">
            <h1>cadastro de @ViewData["Title"]</h1>
    </div>

<form class="cadastro" method="POST" action='@Url.Action("Cadastrar")' enctype="multipart/form-data">

    <div class="campo">
        <label>ID</label>
        <input type="text" name="IdEquipe" />
    </div>  

    <div class="campo">
        <label>Nome</label>
        <input type="text" name="Nome" />
    </div>

    <div class="campo">
        <label>Imagem</label>
        <input type="file" name="Imagem" />
    </div>

    <button class="gradient btn" type="submit">Cadastrar</button>

</form>

<table>
    <thead>
        <th>ID</th>
        <th>Nome</th>
        <th>Foto</th>
        <th>Ações</th>
    </thead>
    <tbody>
        @foreach(Equipe e in ViewBag.Equipes){
            <tr>
                <td>@e.IdEquipe</td>
                <td>@e.Nome</td>
                <td>
                    <img src="img/Equipes/@e.Imagem" alt="Imagem da equipe @e.Nome" width="40">
                </td>
                <td>
                    <a asp-area="" asp-controller="Equipe" asp-action="Excluir" asp-route-id="@e.IdEquipe">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>